// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int currentN = n;
		int over = 0;
		int under = 0;

		while (currentN > 0) {
			double rand = Math.random();
			if (rand > 0.5) {
				over++;
			}
			else {
				under++;
			}
			currentN--;
		}

		
		System.out.println("> 0.5:\t"+n);
		System.out.println("<= 0.5:\t"+over);
		System.out.println("Ratio:\t"+(double) under/over);

	}
}
